const translations = {
    en: {
        // Nav
        'nav.research':     'Research',
        'nav.research.logistics': 'Logistics Optimization',
        'nav.research.production': 'Production Optimization',
        'nav.research.network': 'Network Optimization',
        'nav.research.nextgen': 'Next-Gen Optimization',

        // Research panels
        'research.pubs.label': 'Related Publications',
        'research.ga.label': 'Graphical Abstracts',
        'research.ga.subtitle': 'Selected paper figures',
        'research.ga.open': 'Open full-size',
        'research.ga.logistics.ugvrp.title': 'Generated graphical abstract for VRP with underground transportation',
        'research.ga.logistics.ugvrp.meta': 'IEEE Transactions on Intelligent Transportation Systems, 2025',
        'research.ga.logistics.ugvrp.short': 'Underground VRP',
        'research.ga.logistics.ugvrp.alt': 'Generated graphical abstract showing underground freight transport connected to surface last-mile VRP routes through transfer hubs.',
        'research.ga.logistics.l1.title': 'Multi-flight-level drone routing with altitude-dependent obstacles',
        'research.ga.logistics.l1.meta': 'Computers & Industrial Engineering, 2024',
        'research.ga.logistics.l1.short': 'Flight levels',
        'research.ga.logistics.l1.alt': 'Graphical abstract showing multi-flight-level UAV routes and obstacle layers.',
        'research.ga.logistics.l2.title': 'Urban obstacle-density maps for drone flight-level selection',
        'research.ga.logistics.l2.meta': 'Drone delivery problem with multi-flight level, 2024',
        'research.ga.logistics.l2.short': 'Obstacle maps',
        'research.ga.logistics.l2.alt': 'Paper figure showing obstacle-density maps used for drone flight-level selection.',
        'research.ga.logistics.city.title': 'Urban logistics simulation scene for drone-assisted delivery',
        'research.ga.logistics.city.meta': 'Research visualization for logistics optimization',
        'research.ga.logistics.city.short': 'City simulation',
        'research.ga.logistics.city.alt': 'Simulation scene showing drones and ground vehicles in an urban logistics environment.',
        'research.ga.network.no1.title': 'Climate-adaptive apple supply-chain network design',
        'research.ga.network.no1.meta': 'Systems, 2023',
        'research.ga.network.no1.short': 'Supply chain',
        'research.ga.network.no1.alt': 'Graphical abstract showing climate scenarios and apple supply-chain network flows.',
        'research.ga.network.generated.title': 'Generated graphical abstract for resilient network optimization',
        'research.ga.network.generated.meta': 'Network resilience and smart-grid logistics research visual',
        'research.ga.network.generated.short': 'Resilience',
        'research.ga.network.generated.alt': 'Generated graphical abstract showing disrupted network links, recovery routes, reinforced hubs, and smart-grid logistics integration.',
        'research.ga.network.no2.title': 'Power-grid capacity expansion with renewable and storage planning',
        'research.ga.network.no2.meta': 'Sustainable Energy, Grids and Networks, under review',
        'research.ga.network.no2.short': 'Grid planning',
        'research.ga.network.no2.alt': 'Paper figure showing power-grid expansion, renewable generation, storage, and power-flow planning.',
        'research.ga.production.generated.title': 'Generated graphical abstract for manufacturing and production optimization',
        'research.ga.production.generated.meta': 'Fab logistics, digital twin, FEM, and ML optimization research visual',
        'research.ga.production.generated.short': 'Manufacturing opt.',
        'research.ga.production.generated.alt': 'Generated graphical abstract combining semiconductor fab logistics, digital twin simulation, FEM analysis, and machine-learning process optimization.',
        'research.ga.production.po2.title': 'DNN-GA-MCS framework for blank holder force optimization',
        'research.ga.production.po2.meta': 'The International Journal of Advanced Manufacturing Technology, 2024',
        'research.ga.production.po2.short': 'Process model',
        'research.ga.production.po2.alt': 'Graphical abstract showing sheet-metal forming defects and the DNN-GA-MCS optimization framework.',
        'research.ga.nextgen.generated.title': 'Generated graphical abstract for next-generation optimization algorithms',
        'research.ga.nextgen.generated.meta': 'AI solver, adaptive operators, reinforcement learning, and quantum-inspired optimization visual',
        'research.ga.nextgen.generated.short': 'Advanced opt.',
        'research.ga.nextgen.generated.alt': 'Generated graphical abstract connecting problem encoding, AI solver, adaptive operators, reinforcement-learning feedback, and optimized routes.',
        'research.ga.nextgen.ngo1.title': 'Meta-learning-based adaptive operator selection for TSP',
        'research.ga.nextgen.ngo1.meta': 'Applied Soft Computing, 2025',
        'research.ga.nextgen.ngo1.short': 'Meta-learning',
        'research.ga.nextgen.ngo1.alt': 'Graphical abstract showing meta-learning-based adaptive operator selection for the traveling salesman problem.',

        'research.logistics.desc': 'We research optimal operational strategies for complex logistics systems including urban logistics, drone delivery, underground logistics networks, and Flying Warehouses. Topics include truck-drone hybrid delivery, multi-flight-level drone routing, and urban logistics optimization integrated with underground transportation networks.',
        'research.logistics.intro': 'We pursue three research pillars — drone delivery, underground logistics networks, and simulation-based operational optimization — to reduce the cost and carbon footprint of last-mile delivery.',
        'research.logistics.topic1.title': 'Drone Delivery Optimization',
        'research.logistics.topic1.desc': 'We develop truck-drone hybrid routing (FSTSP / mFSTSP), Flying Warehouse replenishment scheduling, and multi-flight-level drone paths (FL1 20 m / FL2 60 m / FL3 120 m). MILP, ALNS, and ML-based energy models handle real constraints: payload-energy dependency, no-fly zones, and stochastic demand.',
        'research.logistics.topic2.title': 'Underground Logistics Network',
        'research.logistics.topic2.desc': 'We integrate underground capsule and AGV freight tunnels with surface last-mile delivery into a unified multi-modal network. Research covers optimal placement of underground-to-surface transfer hubs, capacity-constrained routing, and simultaneous minimization of carbon emissions and road congestion costs.',
        'research.logistics.topic3.title': 'Operations Optimization & Simulation',
        'research.logistics.topic3.desc': 'VRP variants (CVRP, PDPTW, etc.) are formulated as mathematical programs and solved with ALNS and GRASP metaheuristics at scale. Simulation-based validation tests demand uncertainty, vehicle breakdowns, and traffic scenarios — ensuring algorithms are directly deployable in real operations.',
        'research.logistics.desc1': 'We develop truck-drone hybrid operations and underground-surface network integration that simultaneously reduce cost and carbon emissions in last-mile delivery.',
        'research.logistics.desc2': 'Our methods span MILP and metaheuristic-based multi-flight-level drone routing, real-time replenishment scheduling for airborne Flying Warehouses, and joint design of underground-to-surface multimodal networks. Realistic constraints — payload-energy dependency, no-fly zones, and stochastic demand — are modeled explicitly throughout.',
        'research.logistics.app': 'Amazon · UPS · DHL · Smart City Platforms',
        'research.app.label': 'Applications',
        'research.logistics.tag1': 'Vehicle Routing (VRP)',
        'research.logistics.tag2': 'Drone Delivery',
        'research.logistics.tag3': 'Last-Mile',
        'research.logistics.tag4': 'Flying Warehouse',
        'research.logistics.tag5': 'Underground Logistics',
        'research.logistics.tag6': 'Supply Chain Design',

        'research.network.desc': 'We research the design, operation, and robustness of complex network systems — including supply chain network design and adaptive operations under climate change uncertainty, simulation-based disruption propagation and recovery strategies with network resilience analysis, and integrated V2G-based EV logistics and power distribution network operations.',
        'research.network.desc1': 'Climate disruptions, supply-chain collapses, and rapid EV adoption are creating compounding risks for global logistics and energy networks. We build optimization frameworks that embed resilience from the design stage — applied to food supply chains, defense logistics, and smart-grid operations.',
        'research.network.desc2': 'Research spans climate-scenario-based adaptive supply-chain network design via simulation-optimization, disruption propagation and recovery modeling in interdependent systems, and integrated V2G/G2V EV logistics scheduling with grid capacity expansion. Core methods include stochastic programming, Monte Carlo simulation, and robust optimization.',
        'research.network.topic1.title': 'Climate-Adaptive Supply Chain Design',
        'research.network.topic1.desc': 'We combine climate scenarios, crop and market disruption simulation, and stochastic optimization to redesign sourcing, inventory, and capacity decisions for resilient food supply chains.',
        'research.network.topic2.title': 'Interdependent Network Resilience',
        'research.network.topic2.desc': 'We model how failures propagate across logistics, infrastructure, and mission systems, then optimize repair sequencing, redundancy, and recovery policies under limited resources.',
        'research.network.topic3.title': 'EV-Grid Logistics Operations',
        'research.network.topic3.desc': 'We integrate vehicle routing, charge and discharge schedules, V2G/G2V decisions, and grid capacity planning so EV fleets support both mobility and power-system stability.',
        'research.network.app': 'Food Supply Chain · Defense Logistics · Smart Grid · EV Infrastructure',
        'research.network.tag1': 'Supply Chain Network',
        'research.network.tag2': 'Climate Resilience',
        'research.network.tag3': 'Military Networks',
        'research.network.tag4': 'Network Resilience',
        'research.network.tag5': 'Simulation Optimization',
        'research.network.tag6': 'EV Logistics',
        'research.network.tag7': 'Grid Optimization',

        'research.production.desc': 'We compare and optimize dispatching, path planning, and traffic-control strategies for automated material-handling systems (OHT, AGV, AMR) in advanced manufacturing facilities such as semiconductor fabs through simulation-based methods, and combine this with parameter optimization of manufacturing processes (hot forging, stamping) using machine-learning-integrated FEM simulations to maximize production throughput and efficiency.',
        'research.production.desc1': 'We optimize OHT and AGV dispatching in semiconductor fabs to improve throughput and flow efficiency, and combine FEM simulation with machine learning to enhance process quality in hot forging and deep drawing — contributing to smart-factory transformation in advanced manufacturing.',
        'research.production.desc2': 'We optimize dispatching, routing, and traffic control for automated material-handling systems (OHT, AGV, AMR) via discrete-event simulation. For process optimization, we apply DNN-GA-MCS frameworks to tune blank holder force, temperature, and strain-rate parameters. Instability-map-guided process design and RL-based parameter tuning round out our manufacturing research portfolio.',
        'research.production.topic1.title': 'Fab Logistics Digital Twin',
        'research.production.topic1.desc': 'We reproduce OHT, AGV, and AMR dispatching, routing, and traffic control in semiconductor fabs with discrete-event simulation to reduce congestion and improve tool utilization and throughput.',
        'research.production.topic2.title': 'FEM + ML Process Optimization',
        'research.production.topic2.desc': 'We combine finite-element analysis with DNN-GA-MCS frameworks to tune blank-holder force, temperature, strain-rate, and other process parameters across multiple objectives.',
        'research.production.topic3.title': 'Intelligent Manufacturing Control',
        'research.production.topic3.desc': 'We connect instability maps, reinforcement learning, and quality indicators to reduce defects in hot forging and stamping while designing real-time control policies.',
        'research.production.app': 'Semiconductor Fab · Smart Factory · Automotive Manufacturing',
        'research.production.tag1': 'Hot Forging',
        'research.production.tag2': 'Stamping',
        'research.production.tag3': 'FEM',
        'research.production.tag4': 'Process Optimization',
        'research.production.tag5': 'Quality Control',
        'research.production.tag6': 'Intelligent Manufacturing',

        'research.nextgen.desc': 'We explore future-oriented optimization techniques including combinatorial optimization via meta-learning, reinforcement learning, and neural network-based solvers, as well as quantum computing-based algorithm development. We tackle complex systems problems at the intersection of artificial intelligence and operations research.',
        'research.nextgen.desc1': 'We integrate meta-learning, reinforcement learning, and quantum computing into operations research to solve NP-hard combinatorial problems — TSP, VRP, and beyond — faster and more generally than classical algorithms. AI solvers that instantly adapt to new problem structures hold transformative potential across logistics, scheduling, and network design.',
        'research.nextgen.desc2': 'Our work covers meta-learning-based adaptive large neighborhood search (ALNS), neural-network combinatorial solvers trained via reinforcement learning, and quantum algorithms (QAOA) for optimization. Key research challenges include improving generalization from small benchmark instances to large-scale real-world problems through transfer learning.',
        'research.nextgen.topic1.title': 'Meta-Learning Solvers',
        'research.nextgen.topic1.desc': 'We design meta-learning solvers that automatically select ALNS operators and search strategies from problem features, enabling rapid adaptation to new instances.',
        'research.nextgen.topic2.title': 'Reinforcement Learning Optimization',
        'research.nextgen.topic2.desc': 'We use neural policies and reward design to learn sequential decisions for routing, scheduling, and network design problems, with emphasis on generalization to larger cases.',
        'research.nextgen.topic3.title': 'Quantum-Inspired Optimization',
        'research.nextgen.topic3.desc': 'We apply QAOA and quantum-inspired search to combinatorial optimization models, compare them with classical heuristics, and evaluate hybrid solver potential.',
        'research.nextgen.app': 'Logistics Routing · Production Scheduling · Network Design',
        'research.nextgen.tag1': 'Meta-Learning',
        'research.nextgen.tag2': 'Reinforcement Learning',
        'research.nextgen.tag3': 'Deep Learning',
        'research.nextgen.tag4': 'Quantum Computing',
        'research.nextgen.tag5': 'Combinatorial Optimization',
        'research.nextgen.tag6': 'Artificial Intelligence',

        'nav.publications': 'Publications',
        'nav.pub.international': 'International',
        'nav.pub.domestic':  'Domestic',
        'nav.pub.conference':'Conference',
        'nav.pub.patent':    'Patents',
        'nav.projects':      'Projects',
        'nav.proj.ongoing':  'Ongoing',
        'nav.proj.completed':'Completed',
        'nav.team':          'Members',
        'nav.team.advisor':  'Advisor',
        'nav.team.members':  'Lab Members',
        'nav.team.alumni':   'Alumni',
        'nav.courses':       'Courses',
        'nav.courses.scm':   'Supply Chain Management',
        'nav.courses.ie':    'Intro to IE & Management',
        'nav.community':     'Community',
        'nav.community.news':'News',
        'nav.community.photos':'Photos',
        'nav.community.contact':'Contact',

        // Hero
        'hero.subtitle': 'Pioneering the future of logistics, manufacturing, production, and integrated systems through intelligent optimization.',
        'hero.cta.primary': 'Explore Research',
        'hero.cta.secondary': 'Contact Us',

        // Recruiting
        'recruit.title': 'Join Our Lab',
        'recruit.desc':  'We are looking for motivated researchers passionate about operations research and optimization.',
        'recruit.btn':   'Apply Now',

        // News section
        'news.tag':   'News',
        'news.title': 'Latest News',
        'news.item1.title': 'Lab Website Launch',
        'news.item1.desc':  'The official website of IO-LAB is now live. Stay updated with our latest research and news.',
        'news.viewall': 'View All News →',

        // Contact
        'contact.tag':      'Contact',
        'contact.title':    'Find <span class="highlight">Us</span>',
        'contact.subtitle': 'For research collaborations and inquiries, please reach out via the contact information below.',
        'contact.email':       'Email',
        'contact.office':      "Professor's Office",
        'contact.office.addr': 'Woojung Hall, Room 6034',
        'contact.lab':         'Student Lab',
        'contact.lab.addr':    'Engineering Building, Room 504',

        // Contact page
        'contact.pi.title':       'Principal Investigator',
        'contact.pi.name.label':  'Name',
        'contact.pi.pos.label':   'Position',
        'contact.pi.pos.value':   'Assistant Professor, Dept. of Industrial and Management Systems Engineering, Kyung Hee University',
        'contact.pi.office.label':'Office',
        'contact.pi.office.value':'Woojung Hall 6034, International Campus, Kyung Hee University',
        'contact.pi.email.label': 'Email',
        'contact.pi.phone.label': 'Phone',
        'contact.lab.title':      'Lab Location',
        'contact.lab.addr.label': 'Address',
        'contact.lab.addr.value': '1732 Deogyeong-daero, Giheung-gu, Yongin-si, Gyeonggi-do',
        'contact.lab.loc.label':  'Location',
        'contact.lab.loc.value':  'Engineering Building 504, International Campus, Kyung Hee University',
        'contact.lab.phone.value':'TBA',
        'contact.lab.dir.label':  'Director',
        'contact.join.desc':      'We are looking for motivated researchers passionate about operations research and optimization. Graduate students (M.S./Ph.D.) and undergraduate researchers are welcome.',

        // Footer
        'footer.brand':     'Intelligent Optimization Lab<br>Kyung Hee University',
        'footer.quicklinks':'Quick Links',
        'footer.news':      'News',
        'footer.pubs':      'Publications',
        'footer.projects':  'Projects',
        'footer.team':      'Team',
        'footer.resources': 'Resources',

        // Courses page
        'courses.back':             'Back to Main',
        'courses.title':            'Learning Tools &amp; Practice Materials',
        'courses.scm.name':         'Supply Chain Management',
        'courses.scm.flp.tag':      'Streamlit App · Lab #1',
        'courses.scm.flp.title':    'Facility Location Optimization Platform',
        'courses.scm.flp.desc':     'A practice platform for supply chain network design (facility opening decisions + logistics flow). Submit decision variables in CSV format and compare results on a real-time leaderboard.',
        'courses.scm.flp.features': '<li>2 suppliers, 3 candidate facilities, 4 customers</li><li>Binary variables (facility opening) + continuous variables (flow)</li><li>Minimum cost objective · penalty for constraint violations</li><li>Relative scoring based on 10,000-point maximum</li>',
        'courses.scm.npv.tag':      'Streamlit App · Lab #2',
        'courses.scm.npv.title':    'Demand Forecasting & Warehouse Strategy Game',
        'courses.scm.npv.desc':     'An interactive game where you forecast demand across high/low market states, select warehouse locations and supply strategies, and maximize NPV through adaptive decisions. Experience demand-driven planning and expected value optimization.',
        'courses.scm.npv.features': '<li>High / Low demand state forecasting</li><li>Warehouse location and strategy selection</li><li>Adaptive decisions based on realized demand</li><li>Monte Carlo simulation for strategy comparison</li>',
        'courses.scm.lab3.tag':     'Lab #3',
        'courses.scm.lab3.title':   'Lab #3',
        'courses.scm.lab3.desc':    'This lab material is under preparation.',
        'courses.scm.final.title':  'Final Project',
        'courses.scm.final.desc':   'Final project materials are under preparation.',
        'courses.comingsoon':        'Coming Soon',
        'courses.launch':            'Launch App',
        'courses.ie.name':           'Introduction to IE & Management',
        'courses.ie.download':       'Download Lecture Notes',
        'courses.ie.scm.tag':        'Browser Game · Lab #1',
        'courses.ie.scm.title':      'Global Logistics Management Simulation',
        'courses.ie.scm.desc':       'An educational browser game where you build mines, factories, and sales hubs across 7 world regions, design transportation routes, and maximize profit.',
        'courses.ie.scm.features':   '<li>7 world regions · 3 facility types (mine, factory, sales hub)</li><li>Region-specific demand and market price differentiation</li><li>Transportation route design and cost calculation</li><li>5-round profit/loss simulation</li>',
        'courses.ie.scm.launch':     'Start Game',
        'courses.ie.vrp.tag':        'Browser Game · Lab #2',
        'courses.ie.vrp.title':      'Pickup & Delivery Route Optimization Game',
        'courses.ie.vrp.desc':       'A VRP (Vehicle Routing Problem) practice game where you design pickup and delivery routes for 5 shipments using 2 vehicles and minimize total travel distance.',
        'courses.ie.vrp.features':   '<li>Pickup → delivery precedence constraints</li><li>Vehicle capacity constraint (Capacity = 3)</li><li>Design routes by clicking on the map</li><li>Score vs. benchmark optimal distance · leaderboard</li>',
        'courses.ie.vrp.launch':     'Start Game',
        'courses.ie.lab3.tag':       'Lab #3',
        'courses.ie.lab3.title':     'Lab #3',
        'courses.ie.lab3.desc':      'This lab material is under preparation.',
    },
    ko: {
        // Nav
        'nav.research':     '연구분야',
        'nav.research.logistics': '물류 최적화',
        'nav.research.production': '생산 최적화',
        'nav.research.network': '네트워크 최적화',
        'nav.research.nextgen': '차세대 최적화',

        // Research panels
        'research.pubs.label': '관련 논문',
        'research.ga.label': '그래픽 초록',
        'research.ga.subtitle': '선별된 논문 그림',
        'research.ga.open': '원본 보기',
        'research.ga.logistics.ugvrp.title': '지하 운송 연계 VRP를 위한 생성형 그래픽 초록',
        'research.ga.logistics.ugvrp.meta': 'IEEE Transactions on Intelligent Transportation Systems, 2025',
        'research.ga.logistics.ugvrp.short': '지하 VRP',
        'research.ga.logistics.ugvrp.alt': '지하 화물 운송과 환승 허브를 통해 연결된 지상 라스트마일 VRP 경로를 보여주는 생성형 그래픽 초록입니다.',
        'research.ga.logistics.l1.title': '고도별 장애물을 고려한 다중 비행고도 드론 경로',
        'research.ga.logistics.l1.meta': 'Computers & Industrial Engineering, 2024',
        'research.ga.logistics.l1.short': '비행고도',
        'research.ga.logistics.l1.alt': '다중 비행고도 UAV 경로와 장애물 레이어를 보여주는 그래픽 초록입니다.',
        'research.ga.logistics.l2.title': '드론 비행고도 선택을 위한 도심 장애물 밀도 지도',
        'research.ga.logistics.l2.meta': '다중 비행고도 드론 배송 문제, 2024',
        'research.ga.logistics.l2.short': '장애물 지도',
        'research.ga.logistics.l2.alt': '드론 비행고도 선택에 활용되는 도심 장애물 밀도 지도를 보여주는 논문 그림입니다.',
        'research.ga.logistics.city.title': '드론 보조 배송을 위한 도심 물류 시뮬레이션 장면',
        'research.ga.logistics.city.meta': '물류 최적화 연구 시각화',
        'research.ga.logistics.city.short': '도시 시뮬레이션',
        'research.ga.logistics.city.alt': '도심 물류 환경에서 드론과 지상 차량을 함께 보여주는 시뮬레이션 장면입니다.',
        'research.ga.network.no1.title': '기후 적응형 사과 공급망 네트워크 설계',
        'research.ga.network.no1.meta': 'Systems, 2023',
        'research.ga.network.no1.short': '공급망',
        'research.ga.network.no1.alt': '기후 시나리오와 사과 공급망 네트워크 흐름을 보여주는 그래픽 초록입니다.',
        'research.ga.network.generated.title': '회복탄력적 네트워크 최적화를 위한 생성형 그래픽 초록',
        'research.ga.network.generated.meta': '네트워크 회복탄력성과 스마트그리드 물류 연구 시각화',
        'research.ga.network.generated.short': '회복탄력성',
        'research.ga.network.generated.alt': '장애가 발생한 네트워크 연결, 복구 경로, 강화 허브, 스마트그리드 물류 통합을 보여주는 생성형 그래픽 초록입니다.',
        'research.ga.network.no2.title': '재생에너지와 저장장치를 고려한 전력망 용량 확장 계획',
        'research.ga.network.no2.meta': 'Sustainable Energy, Grids and Networks, 심사 중',
        'research.ga.network.no2.short': '전력망 계획',
        'research.ga.network.no2.alt': '전력망 확장, 재생에너지 발전, 저장장치, 전력 흐름 계획을 보여주는 논문 그림입니다.',
        'research.ga.production.generated.title': '제조 및 생산 최적화를 위한 생성형 그래픽 초록',
        'research.ga.production.generated.meta': '팹 물류, 디지털 트윈, FEM, 머신러닝 최적화 연구 시각화',
        'research.ga.production.generated.short': '제조 최적화',
        'research.ga.production.generated.alt': '반도체 팹 물류, 디지털 트윈 시뮬레이션, FEM 분석, 머신러닝 공정 최적화를 결합한 생성형 그래픽 초록입니다.',
        'research.ga.production.po2.title': '블랭크홀더 힘 최적화를 위한 DNN-GA-MCS 프레임워크',
        'research.ga.production.po2.meta': 'The International Journal of Advanced Manufacturing Technology, 2024',
        'research.ga.production.po2.short': '공정 모델',
        'research.ga.production.po2.alt': '판재 성형 결함과 DNN-GA-MCS 최적화 프레임워크를 보여주는 그래픽 초록입니다.',
        'research.ga.nextgen.generated.title': '차세대 최적화 알고리즘을 위한 생성형 그래픽 초록',
        'research.ga.nextgen.generated.meta': 'AI 솔버, 적응형 연산자, 강화학습, 양자 영감 최적화 연구 시각화',
        'research.ga.nextgen.generated.short': '차세대 최적화',
        'research.ga.nextgen.generated.alt': '문제 인코딩, AI 솔버, 적응형 연산자, 강화학습 피드백, 최적 경로를 연결한 생성형 그래픽 초록입니다.',
        'research.ga.nextgen.ngo1.title': 'TSP를 위한 메타러닝 기반 적응형 연산자 선택',
        'research.ga.nextgen.ngo1.meta': 'Applied Soft Computing, 2025',
        'research.ga.nextgen.ngo1.short': '메타러닝',
        'research.ga.nextgen.ngo1.alt': '외판원 문제를 위한 메타러닝 기반 적응형 연산자 선택 과정을 보여주는 그래픽 초록입니다.',

        'research.logistics.desc': '도시 물류, 드론 배송, 지하 물류 네트워크, 비행 창고(Flying Warehouse) 등 복잡한 물류 시스템에서 최적 운영 전략을 연구합니다. 차량-드론 복합 배송, 다중 비행 수준(multi-flight level) 드론 경로 설계, 지하 운송망과 연계된 도시 물류 최적화 등을 다룹니다.',
        'research.logistics.intro': '드론 배송, 지하 물류 네트워크, 시뮬레이션 기반 운영 최적화 세 축을 통해 라스트마일 배송의 비용·탄소 배출을 줄이는 연구를 수행합니다.',
        'research.logistics.topic1.title': '드론 배송 최적화',
        'research.logistics.topic1.desc': '트럭-드론 복합 경로(FSTSP/mFSTSP), 비행 창고(Flying Warehouse) 기반 보충 스케줄링, 다중 비행 수준(FL1 20m / FL2 60m / FL3 120m) 드론 경로 최적화를 연구합니다. MILP·ALNS·ML 에너지 모델을 결합해 페이로드-에너지 의존성과 No-fly zone 제약을 현실적으로 다룹니다.',
        'research.logistics.topic2.title': '지하 물류 네트워크',
        'research.logistics.topic2.desc': '도심 지하를 활용한 화물 캡슐·AGV 터널망과 지상 라스트마일 구간을 통합 설계합니다. 지하-지상 복합 환승 거점 배치, 용량 제약 하의 경로 최적화, 탄소 배출 및 도로 혼잡 비용 동시 절감을 목표로 합니다.',
        'research.logistics.topic3.title': '운영 최적화 & 시뮬레이션',
        'research.logistics.topic3.desc': 'VRP 및 변형 문제(CVRP, PDPTW 등)를 수리 모델로 정식화하고 ALNS·GRASP 메타휴리스틱으로 대규모 인스턴스를 해결합니다. 시뮬레이션 기반 검증으로 수요 불확실성·차량 고장·교통 혼잡 시나리오를 평가하여 실 운영에 바로 적용 가능한 알고리즘을 제공합니다.',
        'research.logistics.desc1': '트럭-드론 복합 운영과 지하 물류망을 결합해 라스트마일 배송의 비용과 탄소 배출을 동시에 줄이는 방법론을 연구합니다.',
        'research.logistics.desc2': 'MILP 및 메타휴리스틱 기반의 다중 비행 수준(multi-flight level) 드론 경로 최적화, 비행 창고(Flying Warehouse)의 실시간 보충 스케줄링, 지하-지상 복합 운송 네트워크 설계를 연구합니다. 페이로드-에너지 의존성, No-fly zone 제약, 수요 불확실성을 고려한 현실적 모델링이 핵심입니다.',
        'research.logistics.app': 'Amazon · UPS · DHL · 스마트시티 플랫폼',
        'research.app.label': '적용 분야',
        'research.logistics.tag1': '차량 경로 (VRP)',
        'research.logistics.tag2': '드론 배송',
        'research.logistics.tag3': '라스트마일',
        'research.logistics.tag4': '비행 창고',
        'research.logistics.tag5': '지하 물류',
        'research.logistics.tag6': '공급망 설계',

        'research.network.desc': '기후변화 불확실성을 고려한 공급망(supply chain network) 설계 및 적응형 운영 전략, 시뮬레이션 기반 장애 전파·복구 전략과 네트워크 회복력(resilience) 분석, V2G 기반 EV 물류·배전망 통합 운영 등 복잡한 네트워크 시스템의 설계·운영·강건성을 연구합니다.',
        'research.network.desc1': '기후변화, 공급망 붕괴, EV 대중화 등 복합 리스크가 글로벌 네트워크를 위협하는 시대에, 설계 단계부터 회복력(resilience)을 내재화하는 최적화 방법론을 개발합니다. 식품 공급망, 군사 물류, 스마트그리드 등 임무 중요(mission-critical) 분야에 직접 적용됩니다.',
        'research.network.desc2': '기후 시나리오 기반 적응형 공급망 설계(시뮬레이션-최적화), 상호의존 시스템에서의 장애 전파·복구 전략 모델링, V2G/G2V 통합 EV 물류 스케줄링과 배전망 용량 확장 최적화를 연구합니다. 확률적 프로그래밍, 몬테카를로 시뮬레이션, 강건 최적화가 핵심 방법론입니다.',
        'research.network.topic1.title': '기후 적응형 공급망 설계',
        'research.network.topic1.desc': '기후 시나리오와 작황·시장 교란 시뮬레이션, 확률적 최적화를 결합해 식품 공급망의 조달·재고·용량 결정을 회복력 있게 재설계합니다.',
        'research.network.topic2.title': '상호의존 네트워크 회복력',
        'research.network.topic2.desc': '물류·인프라·임무 시스템 사이에서 장애가 전파되는 과정을 모델링하고, 제한된 자원하에서 복구 순서·중복성·회복 정책을 최적화합니다.',
        'research.network.topic3.title': 'EV-전력망 통합 운영',
        'research.network.topic3.desc': '차량 경로, 충·방전 스케줄, V2G/G2V 의사결정, 배전망 용량 계획을 통합해 EV 물류가 이동성과 전력망 안정성을 함께 지원하도록 설계합니다.',
        'research.network.app': '식품 공급망 · 군사 물류 · 스마트그리드 · EV 인프라',
        'research.network.tag1': '공급망 네트워크',
        'research.network.tag2': '기후변화 대응',
        'research.network.tag3': '군사 네트워크',
        'research.network.tag4': '네트워크 회복력',
        'research.network.tag5': '시뮬레이션 최적화',
        'research.network.tag6': 'EV 물류',
        'research.network.tag7': '배전망 최적화',

        'research.production.desc': '반도체 팹 등 첨단 제조 시설의 자동화 물류 시스템(OHT, AGV, AMR) 배차·경로 최적화·교통 제어 전략을 시뮬레이션 기반으로 비교·최적화하고, 열간 단조·스탬핑 등 제조 공정의 파라미터 최적화 및 머신러닝 통합 FEM 시뮬레이션을 결합하여 생산 처리량과 효율을 극대화하는 연구를 수행합니다.',
        'research.production.desc1': '반도체 팹 내 OHT·AGV 배차 최적화를 통해 생산 처리량과 흐름 효율을 개선하고, FEM 시뮬레이션과 머신러닝을 결합한 공정 최적화로 열간 단조·딥드로잉의 품질을 향상시킵니다. 첨단 제조 현장의 스마트팩토리 전환에 기여하는 연구입니다.',
        'research.production.desc2': '반도체 팹 자동화 물류(OHT, AGV, AMR)의 배차·경로·교통 제어를 이산사건 시뮬레이션으로 최적화하고, DNN-GA-MCS 프레임워크로 블랭크홀더 하중·온도·변형률 파라미터를 튜닝합니다. 불안정도 맵(instability map)과 강화학습을 결합한 열간 단조 공정 설계도 핵심 연구 주제입니다.',
        'research.production.topic1.title': '팹 물류 디지털 트윈',
        'research.production.topic1.desc': '반도체 팹의 OHT·AGV·AMR 배차, 경로, 교통 제어를 이산사건 시뮬레이션으로 재현해 혼잡을 줄이고 장비 가동률과 처리량을 높입니다.',
        'research.production.topic2.title': 'FEM+ML 공정 최적화',
        'research.production.topic2.desc': '유한요소 해석과 DNN-GA-MCS 프레임워크를 결합해 블랭크홀더 하중, 온도, 변형률 속도 등 핵심 공정 파라미터를 다목적으로 조정합니다.',
        'research.production.topic3.title': '지능형 제조 제어',
        'research.production.topic3.desc': '불안정도 맵, 강화학습, 품질 지표를 연결해 열간 단조·스탬핑 공정의 결함을 줄이고 실시간 제어 정책을 설계합니다.',
        'research.production.app': '반도체 팹 · 스마트팩토리 · 자동차 부품 제조',
        'research.production.tag1': '열간 단조',
        'research.production.tag2': '스탬핑',
        'research.production.tag3': '유한요소법 (FEM)',
        'research.production.tag4': '공정 최적화',
        'research.production.tag5': '품질 제어',
        'research.production.tag6': '지능형 제조',

        'research.nextgen.desc': '메타러닝(meta-learning), 강화학습, 신경망 기반 해법을 활용한 조합 최적화 문제 해결 및 양자 컴퓨팅(quantum computing) 기반 알고리즘 개발 등 미래 지향적 최적화 기법을 연구합니다. 인공지능과 운영과학의 융합을 통해 복잡계 문제에 도전합니다.',
        'research.nextgen.desc1': 'NP-hard 조합 최적화 문제(TSP, VRP 등)를 기존 알고리즘보다 빠르고 범용적으로 풀기 위해 메타러닝, 강화학습, 양자 컴퓨팅을 운영과학에 접목합니다. 새로운 문제 유형에 즉각 적응하는 AI 솔버는 물류, 스케줄링, 네트워크 설계 전반에서 패러다임을 바꿀 잠재력을 지닙니다.',
        'research.nextgen.desc2': '메타러닝 기반 적응형 대규모 이웃 탐색(ALNS), 강화학습 기반 신경망 조합 최적화 해법기, QAOA 등 양자 알고리즘의 조합 최적화 적용을 연구합니다. 소규모 인스턴스에서 대규모 실문제로의 일반화 성능과 전이 학습이 핵심 연구 과제입니다.',
        'research.nextgen.topic1.title': '메타러닝 해법기',
        'research.nextgen.topic1.desc': '문제 특성에 따라 ALNS 연산자와 탐색 전략을 자동 선택하는 메타러닝 기반 솔버를 설계해 새로운 인스턴스에 빠르게 적응합니다.',
        'research.nextgen.topic2.title': '강화학습 최적화',
        'research.nextgen.topic2.desc': '신경망 정책과 보상 설계를 활용해 경로, 스케줄, 네트워크 설계 문제의 순차적 의사결정을 학습하고 대규모 문제로 일반화합니다.',
        'research.nextgen.topic3.title': '양자 영감 최적화',
        'research.nextgen.topic3.desc': 'QAOA와 양자 영감 탐색을 조합 최적화 모델에 적용해 고전적 휴리스틱과 비교하고, 하이브리드 솔버의 활용 가능성을 평가합니다.',
        'research.nextgen.app': '물류 라우팅 · 생산 스케줄링 · 네트워크 설계',
        'research.nextgen.tag1': '메타러닝',
        'research.nextgen.tag2': '강화학습',
        'research.nextgen.tag3': '딥러닝',
        'research.nextgen.tag4': '양자 컴퓨팅',
        'research.nextgen.tag5': '조합 최적화',
        'research.nextgen.tag6': '인공지능',

        'nav.publications': '논문',
        'nav.pub.international': '국제 논문',
        'nav.pub.domestic':  '국내 논문',
        'nav.pub.conference':'학회지',
        'nav.pub.patent':    '특허',
        'nav.projects':      '연구과제',
        'nav.proj.ongoing':  '진행중인 과제',
        'nav.proj.completed':'완료한 과제',
        'nav.team':          '구성원',
        'nav.team.advisor':  '지도교수',
        'nav.team.members':  '연구원',
        'nav.team.alumni':   '졸업생',
        'nav.courses':       '교육자료',
        'nav.courses.scm':   '공급사슬관리',
        'nav.courses.ie':    '산업경영공학의 이해',
        'nav.community':     '커뮤니티',
        'nav.community.news':'소식',
        'nav.community.photos':'사진',
        'nav.community.contact':'연락처',

        // Hero
        'hero.subtitle': '지능형 최적화를 통해 물류, 제조, 생산 및 통합 시스템의 미래를 개척합니다.',
        'hero.cta.primary': '연구 분야 보기',
        'hero.cta.secondary': '문의하기',

        // Recruiting
        'recruit.title': '연구진 모집',
        'recruit.desc':  '운영과학과 최적화에 열정을 가진 동기부여된 연구자를 찾고 있습니다.',
        'recruit.btn':   '지원하기',

        // News
        'news.tag':   '소식',
        'news.title': '최신 소식',
        'news.item1.title': '연구실 홈페이지 오픈',
        'news.item1.desc':  'Intelligent Optimization LAB (IO-LAB)의 공식 홈페이지를 오픈했습니다. 연구실의 최신 연구 성과와 소식을 확인하실 수 있습니다.',
        'news.viewall': '전체 소식 보기 →',

        // Contact
        'contact.tag':      '연락처',
        'contact.title':    '찾아오시는 <span class="highlight">길</span>',
        'contact.subtitle': '연구 협력 및 문의는 아래 연락처로 연락해 주세요.',
        'contact.email':       '이메일',
        'contact.office':      '교수 연구실',
        'contact.office.addr': '우정원 6034호',
        'contact.lab':         '학생 연구실',
        'contact.lab.addr':    '공학관 504호',

        // Contact page
        'contact.pi.title':       '연구책임자',
        'contact.pi.name.label':  '이름',
        'contact.pi.pos.label':   '직위',
        'contact.pi.pos.value':   '조교수, 경희대학교 산업경영공학과',
        'contact.pi.office.label':'연구실',
        'contact.pi.office.value':'경희대학교 국제캠퍼스 우정원 6034',
        'contact.pi.email.label': '이메일',
        'contact.pi.phone.label': '전화',
        'contact.lab.title':      '연구실',
        'contact.lab.addr.label': '주소',
        'contact.lab.addr.value': '경기도 용인시 기흥구 덕영대로 1732',
        'contact.lab.loc.label':  '위치',
        'contact.lab.loc.value':  '경희대학교 국제캠퍼스 공학관 504',
        'contact.lab.phone.value':'추후 공개',
        'contact.lab.dir.label':  '책임자',
        'contact.join.desc':      '운영과학과 최적화에 열정을 가진 동기부여된 연구자를 찾고 있습니다. 대학원생(석·박사) 및 학부연구생 모집 중입니다.',

        // Footer
        'footer.brand':     '지능형 최적화 연구실<br>경희대학교',
        'footer.quicklinks':'빠른 링크',
        'footer.news':      '소식',
        'footer.pubs':      '논문',
        'footer.projects':  '연구과제',
        'footer.team':      '연구진',
        'footer.resources': '자료',

        // Courses page
        'courses.back':             '메인으로 돌아가기',
        'courses.title':            '학습 도구 &amp; 실습 자료',
        'courses.scm.name':         '공급사슬관리',
        'courses.scm.flp.tag':      'Streamlit App · 실습 #1',
        'courses.scm.flp.title':    '시설입지 최적화 경쟁 플랫폼',
        'courses.scm.flp.desc':     '공급망 네트워크 설계(시설 개설 결정 + 물류 흐름)를 주제로 한 실습 플랫폼입니다. CSV 형식으로 의사결정변수를 제출하고 실시간 리더보드에서 최적화 결과를 비교합니다.',
        'courses.scm.flp.features': '<li>공급자 2곳, 후보 시설 3곳, 고객 4곳</li><li>이진 변수(시설 개설) + 연속 변수(물류 흐름)</li><li>최소 비용 목적함수 · 제약 위반 시 페널티 부과</li><li>최고점 10,000점 기준 상대 채점</li>',
        'courses.scm.npv.tag':      'Streamlit App · 실습 #2',
        'courses.scm.npv.title':    '수요 예측 & 창고 전략 게임',
        'courses.scm.npv.desc':     '고수요/저수요 시장 상태를 예측하고, 창고 입지 및 공급 전략을 선택하여 NPV를 극대화하는 인터랙티브 게임입니다. 수요 기반 계획 수립과 기대값 최적화를 직접 체험합니다.',
        'courses.scm.npv.features': '<li>고수요 / 저수요 상태 수요 예측</li><li>창고 입지 및 전략 선택</li><li>실현 수요에 따른 적응형 의사결정</li><li>몬테카를로 시뮬레이션으로 전략 비교</li>',
        'courses.scm.lab3.tag':     '실습 #3',
        'courses.scm.lab3.title':   '실습 #3',
        'courses.scm.lab3.desc':    '준비 중인 실습 자료입니다.',
        'courses.scm.final.title':  '기말 프로젝트',
        'courses.scm.final.desc':   '준비 중인 기말 프로젝트 자료입니다.',
        'courses.comingsoon':        '준비중',
        'courses.launch':            '앱 실행',
        'courses.ie.name':           '산업경영공학의 이해',
        'courses.ie.download':       '강의자료 다운로드',
        'courses.ie.scm.tag':        'Browser Game · 실습 #1',
        'courses.ie.scm.title':      '글로벌 물류 경영 시뮬레이션',
        'courses.ie.scm.desc':       '7개 세계 지역에서 광산·공장·판매거점을 건설하고 운송 경로를 설계하여 수익을 극대화하는 교육용 브라우저 게임입니다.',
        'courses.ie.scm.features':   '<li>7개 세계 지역 · 광산·공장·판매거점 3종 시설</li><li>지역별 수요 및 시장가격 차별화</li><li>운송 경로 설계 및 비용 계산</li><li>5 라운드 기반 손익 시뮬레이션</li>',
        'courses.ie.scm.launch':     '게임 시작',
        'courses.ie.vrp.tag':        'Browser Game · 실습 #2',
        'courses.ie.vrp.title':      '픽업 & 배송 경로 최적화 게임',
        'courses.ie.vrp.desc':       '2대의 차량으로 5개 화물의 픽업·배송 경로를 직접 설계하고, 총 이동 거리를 최소화하는 VRP(Vehicle Routing Problem) 실습 게임입니다.',
        'courses.ie.vrp.features':   '<li>픽업 → 배송 선행 제약 조건 (Precedence Constraint)</li><li>차량 적재 용량 제약 (Capacity = 3)</li><li>지도 위 클릭으로 경로 직접 구성</li><li>기준 최적 거리 대비 점수 산출 및 리더보드</li>',
        'courses.ie.vrp.launch':     '게임 시작',
        'courses.ie.lab3.tag':       '실습 #3',
        'courses.ie.lab3.title':     '실습 #3',
        'courses.ie.lab3.desc':      '준비 중인 실습 자료입니다.',
    }
};

function applyLang(lang) {
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (translations[lang] && translations[lang][key] !== undefined) {
            el.textContent = translations[lang][key];
        }
    });
    document.querySelectorAll('[data-i18n-html]').forEach(el => {
        const key = el.getAttribute('data-i18n-html');
        if (translations[lang] && translations[lang][key] !== undefined) {
            el.innerHTML = translations[lang][key];
        }
    });

    // Update toggle button state
    document.querySelectorAll('.lang-option').forEach(btn => {
        btn.classList.toggle('active', btn.dataset.lang === lang);
    });

    localStorage.setItem('io-lab-lang', lang);
    document.documentElement.lang = lang;
    window._currentLang = lang;
    document.dispatchEvent(new CustomEvent('io-lab-lang-change', { detail: { lang } }));
}

function toggleLang(lang) {
    applyLang(lang);
}

document.addEventListener('DOMContentLoaded', () => {
    const saved = localStorage.getItem('io-lab-lang') || 'en';
    applyLang(saved);
});
